### ISSUE TITLE
Memory leak when using Gtk+-3.18.2

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2990]
As reported in the forum:
http://rawtherapee.com/forum/viewtopic.php?f=1&t=5738&start=45#p44287

RawTherapee 4.2.526 branch:gtk3 in Fedora 23 uses Gtk+ 3.18.2 and is reported to have a serious memory leak.

**Comment by Beep6581** [comment]
Finding the cause of memory leaks is slow work because we need to run RawTherapee from within a program called valgrind which makes every single action EXTREMELY slow (opening a folder takes 5 minutes, opening a raw image can take half an hour... you get the picture).
To help us, please do this:

1. Create a folder with the minimal number of raw images necessary to trigger the memleak - e.g. is 1 enough? If not, are 10 enough? And if 10 are enough, do they need to be unique, or can you copy the same raw image and paste it 10 times under different names? Please try with this raw file http://rawtherapee.com/shared/test_images/amsterdam.pef

2. Use a tool which shows you memory usage. KDE has KSysGuard, GNOME has System Monitor. That way you can see when memory usage starts to increase. Send us a screenshot.

3. Describe exactly what you do to trigger it, from the moment you launched RT, e.g. "I started RawTherapee, I double-clicked on /tmp/foo in RawTherapee's file browser, and after the thumbnail(s) loaded I saw that memory usage in KSysGuard kept increasing. I didn't need to open any of the raw files in the Editor."

**Comment by Coasting** [comment]
Tests done in Fedora 23, with the RT-gtk3 branch, RT 4.2.526, installed from the Fedora 23 yum repo Nov 26, 2015. The same results were found from RT 4.2.526 compiled on the test machine.

With the startup folder empty, RT opens with a slight bump in the amount of memory used but memory used is flat and minor after a short time. 

With the startup folder containing one copy of the .pef file (above) and no .pp3 in the folder, opening RT causes additional cpu activity that continues indefinitely and the memory used climbs continuously at a modest rate. This is shown in gnome system monitor:
![b](https://cloud.githubusercontent.com/assets/16050011/11448902/a7a3a2fa-9518-11e5-8cca-678434fcdef1.png)
Exiting RT returns memory to the previous level before opening RT.

With 4 copies of the .pef file (different names) in the startup folder memory usage climbs more rapidly and continuous cpu use is a bit higher.
![d](https://cloud.githubusercontent.com/assets/16050011/11448930/66ebf9a0-9519-11e5-9b5f-d0e220030605.png)

From an empty startup folder, double clicking on the folder with the pef files displays the thumbnails and starts the memory climbing as it does when starting up with them in the startup folder.

I didn't need to open any files in the Editor to trigger the memory leak.

**Comment by heckflosse** [comment]
Thanks for detailed report.
I'll try to reproduce (and valgrind) at my Sabayon-machine using Gtk+-3.18.2 at the weekend.

ingi

**Comment by mbajor** [comment]
I launched RT with 93 thumbnails in valgrdind with --tool=massif option. Note that RT consumes memory only if is foreground - minimized or below other windows not.
![rt-massif](https://cloud.githubusercontent.com/assets/628108/11452617/e67ff268-95ee-11e5-81cd-11a8eca89c78.png)
[massif output file](https://drive.google.com/file/d/0B2-C_Gk2B3IZdlNUWlc3MW5mWnM/view?usp=sharing)

**Comment by Hombre57** [comment]
On line 67 of rtgui/thumbbrowserentrybase.cc, a new BackBuffer is created and assigned to the backBuffer parameter, while it may already handle a BackBuffer.

I don't know the internal of RefPtr, but maybe the difference in behavior lies in the fact that one version delete the actual BackBuffer before assigning the new one. (just a guess)

To correct the bug, please replace line 67 of  by rtgui/thumbbrowserentrybase.cc :

------------------------------------------------------------------------------------------------------
    if (backBuffer && (backBuffer->getWidth() != exp_width || backBuffer->getHeight() != exp_height )) {
        // deleting the existing BackBuffer
        backBuffer.reset();
    }
    if (!backBuffer) {
        backBuffer = Glib::RefPtr<BackBuffer> ( new BackBuffer (exp_width, exp_height, win) );
    }
------------------------------------------------------------------------------------------------------

This will be even better than the "working solution", because it will not delete the BackBuffer if it already has the correct dimensions.

The collateral side effect of this bugfix is that I can launch RT now : it doesn't crash anymore right after starting, but it still behave very oddly...

**Comment by Hombre57** [comment]
Since it seems to correct an obvious bug at let me start RT now, I pushed the fix.

**Comment by adamreichold** [comment]
I think I see related continuous CPU load from the `gtk3` branch as long as the window is visible. It seems like the thumbnail backbuffers are never marked clean after being marked dirty? I would lie if I said I fully understood the current implementation, but
````
diff --git a/rtgui/thumbbrowserentrybase.cc b/rtgui/thumbbrowserentrybase.cc
index 5f928a7..fdc30f2 100644
--- a/rtgui/thumbbrowserentrybase.cc
+++ b/rtgui/thumbbrowserentrybase.cc
@@ -285,6 +285,8 @@ void ThumbBrowserEntryBase::updateBackBuffer ()
             }
         }
     }
+
+    backBuffer->setDirty(false);
 }
 
 void ThumbBrowserEntryBase::getTextSizes (int& infow, int& infoh)
````
did stop most of the continuous updating for me. (Meaning down from constantly 60% to 10% CPU when the window is visible.)

**Comment by Hombre57** [comment]
Well spotted ! I missed to set that flag to false :S

Patch committed.

Leaved opened but I think it's done now. Coasting, mbajor, do you confirm ?

**Comment by adamreichold** [comment]
To clarify my understanding of about the above changes: I think the constant redrawing, i.e. the calls to `ThumbBrowserEntryBase::draw` are still happening, it is just that we do not allocate new back buffers or with the second change update those back buffers all the time. This also explains the residual CPU load I am seeing and I think finding out why `ThumbBrowserEntryBase::Internal::on_draw` is called again and again is central to solving this issue.

**Comment by Hombre57** [comment]
updateBackBuffer may be called on each FileBrowserEntry::motionNotify event, in some situation.

If you only move the mouse over the thumbnail image but still see the it is constantly updating the thumbnail, then it is clearly a bug. But updating the thumbnail when moving over the thumbnail's widgets is normal.

**Comment by Hombre57** [comment]
Hmmm, having a second read on your comment, I'm afraid that I don't really understand it (English is not my mother's language...).

**Comment by adamreichold** [comment]
Well, I am pretty much baffled by how this works, but it seems like the call to `sc->get_background_color(Gtk::STATE_FLAG_SELECTED)` in `ThumbBrowserEntryBase::draw` is what triggers the endless loop of redrawing `ThumbBrowserBase::internal`. If I remove just this call, i.e.
````
diff --git a/rtgui/thumbbrowserentrybase.cc b/rtgui/thumbbrowserentrybase.cc
index fdc30f2..e2b3ae8 100644
--- a/rtgui/thumbbrowserentrybase.cc
+++ b/rtgui/thumbbrowserentrybase.cc
@@ -501,7 +501,7 @@ void ThumbBrowserEntryBase::draw ()
 //  Gdk::RGBA textn = sc->get_color(Gtk::STATE_FLAG_NORMAL);
 //  Gdk::RGBA texts = sc->get_color(Gtk::STATE_FLAG_SELECTED);
     Gdk::RGBA bgn = sc->get_background_color(Gtk::STATE_FLAG_NORMAL);
-    Gdk::RGBA bgs = sc->get_background_color(Gtk::STATE_FLAG_SELECTED);
+    Gdk::RGBA bgs = bgn;//sc->get_background_color(Gtk::STATE_FLAG_SELECTED);
     int w_ = startx + ofsX;
     int h_ = starty + ofsY;
     cc->set_source(backBuffer->getSurface(), w_, h_);
````
then CPU load will go to zero percent after some time even if the window is visible and break points within `ThumbBrowserBase::Internal::on_draw` are not hit anymore. The call to `sc->get_background_color(Gtk::STATE_FLAG_NORMAL)` does not seem to have a similar effect.

From looking at the GTK+ source, I'd say this is somehow rooted in the CSS theme machinery. In any case, the method itself seems to be marked deprecated and should probably be replaced (e.g. its usage folded into `LWButtonSet::redraw` by using `Gtk::StyleContext::render_background`)?

P.S.: While looking into this, I noticed the `RefCount` helper class used by `BackBuffer`. I think this one does [object slicing](https://en.wikipedia.org/wiki/Object_slicing) by calling the non-virtual destructor of `BackBuffer` using `RefCount::this`, i.e. by pointer-to-base, within `RefCount::unreference`. I'd say either `RefCount` mandates a virtual destructor for its children by making its own destructor virtual which is probably the safe choice or one uses the [CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) in which case only the most derived class can safely inherit from `RefCount`, e.g.
````
template< typename T >
class RefCount
{
public:
  void unreference()
  {
    if (!--refCount)
      delete static_cast<T*>(this);
  }
};

class BackBuffer final : public RefCount<BackBuffer>
{
};
````
which however in this case does not work as e.g. `ColoredBar` derives from `BackBuffer` which however looks like a [misuse of inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) at a first glance as I would expect a `ColoredBar` to have a `BackBuffer` instead of being a kind of.

**Comment by Hombre57** [comment]
Yes, that's an odd behavior. But if you look at how things are done in the GUI, when going over a thumbnail icons, it draw a frame around it. The color of this frame is either the fg color of its parent object if the thumb is not selected, or the bg color of this same object if it is selected. In Gtk2, each color could be used in the way we wanted, but that will not be the case anymore. Having to use "render_xxx" instead of also being able to simply get the color and use it the way we want is a regression to me.

For the object slicing, I had to add RefCount as parent class of BackBuffer to be able to handle the object through Glib::RefPtr (otherwise it wouldn't even build), that's what I've found after some Googling. If this is wrong, then how do we use Glib::RefPtr with custom classes ? Feel free to set this correctly then, since by all evidence, you have more knowledge in C++ programming than me (seriously speaking).

For the ColoredBar class, it is used as a back-buffer in the objects that it is included 'in', so it makes sens to me to let it 'be' a BackBuffer. Could you elaborate on why it's a misuse of inheritance ? Btw, BackBuffer was not a children of RefCount in the RT/Gtk2 times, so maybe I've half done the job.

**Comment by adamreichold** [comment]
> In Gtk2, each color could be used in the way we wanted, but that will not be the case anymore. Having to use "render_xxx" instead of also being able to simply get the color and use it the way we  want is a regression to me.

From the GTK+ documentation, I'd say that the motivation is that a background can be a number of things besides a plain colour when using CSS themes. Hence if one cannot assume that, painting the background is an opaque operation which is the API that GTK+ now provides. This might also be the explanation why calling `sc->get_background_color(Gtk::STATE_FLAG_SELECTED)` has side-effects when determining the colour.

> For the object slicing, I had to add RefCount as parent class of BackBuffer to be able to handle the object through Glib::RefPtr (otherwise it wouldn't even build), that's what I've found after some Googling. If this is wrong, then how do we use Glib::RefPtr with custom classes ? Feel free to set this correctly then, since by all evidence, you have more knowledge in C++ programming than me (seriously speaking).

I don't think the idea of using reference count mix-in is wrong, quite the opposite. It is just that deleting by pointer-to-base is dangerous in C++ as methods are non-virtual by default (due to the performance overhead of virtual calls). Reading the glibmm documentation, I'd say a virtual destructor is the way to go, i.e. `Glib::RefPtr<T>` seems to be normally used with subclasses of `Glib::ObjectBase` which defines a pure virtual destructor `virtual ~ObjectBase () noexcept=0` in addition to the `reference` and `unreference` method. So I'd suggest applying
````
diff --git a/rtgui/guiutils.h b/rtgui/guiutils.h
index 8c2137b..ec1b44a 100644
--- a/rtgui/guiutils.h
+++ b/rtgui/guiutils.h
@@ -496,6 +496,7 @@ private:
     int refCount;
 public:
     RefCount() : refCount(1) {}
+    virtual ~RefCount() {}
 
     void reference()
     {
````
as the most simple and safe solution.

> For the ColoredBar class, it is used as a back-buffer in the objects that it is included 'in', so it makes sens to me to let it 'be' a BackBuffer. Could you elaborate on why it's a misuse of inheritance ? Btw, BackBuffer was not a children of RefCount in the RT/Gtk2 times, so maybe I've half done the job.

Usually a subtype relation should only be used if the subtype fulfils the [substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), i.e. it can sensibly be used everywhere that its supertype can, as this is what the type system tries to enforce. But AFAIU it usually makes no sense to replace some arbitrary `BackBuffer` by a `ColoredBar` because a `ColoredBar` is not just some other kind of back buffer providing exactly the same semantics but a whole different thing even though it might provide some similar services (e.g. think of replacing `Glib::RefPtr<BackBuffer> ThumbBrowserEntryBase::backBuffer` by `Glib::RefPtr<ColoredBar> ThumbBrowserEntryBase::backBuffer`).
What is currently achieved by the inheritance is that the code from `BackBuffer` to implement those services is reused, but non-polymorphic code reuse is usually not done by inheritance, at least not by public inheritance. In C++ one could use private inheritance but without any major benefits in comparison with just giving the `ColoredBar` a field of type `BackBuffer` and forwarding exactly those methods that should be available to users of `ColoredBar` to that instance (any maybe intercepting arguments to enforce contracts and such stuff). Of course, one would write a bit more boiler plate, but the type system would then not allow one to use a `ColoredBar` where a general back buffer is needed so that e.g. the content drawn of `ColoredBar::draw` cannot interfere with some other content drawn onto that surface.
As a more concrete example of why a more a segregated interface might be useful, consider that the methods `BackBuffer::setDrawRectangle` and `ColoredBar::expose` seem to be usually called together. Why not offer a single method `ColoredBar::exposeRectangle` so that users of this class have a harder time doing it wrong and the same call sequence is not repeated so often.
The general idea is IMHO that the semantics of your types and the rules of the type system should be as closely aligned as possible. (Of course, usually the type system is much weaker than your type's semantics.)

P.S.: Maybe the following patch would also be useful for the `gtk3` branch, as those deprecation warning currently drown out all other warnings:
````
diff --git a/rtgui/guiutils.h b/rtgui/guiutils.h
index 8c2137b..044b6e5 100644
--- a/rtgui/guiutils.h
+++ b/rtgui/guiutils.h
@@ -39,40 +39,11 @@ void setExpandAlignProperties(Gtk::Widget *widget, bool hExpand, bool vExpand, e
 
 guint add_idle (GSourceFunc function, gpointer data);
 
-/**
- * @brief Lock GTK for critical section.
- *
- * Will unlock on destruction. To use:
- *
- *   <code>
- *     {
- *       GThreadLock lock;
- *       // critical code
- *     }
- *   </code>
- *
- *   This is a replacement for the former gdk_threads_enter / gdk_threads_leave pair that has been deprecated.
- *   It does the same, but there may be a speed penalty, hopefully negligible.
- */
-
-/*
- *
- *    This, doesn't work. But we have to find a replacement for gdk_threads_enter and gdk_threads_leave that are depr
- *
- *
-class GThreadLock
-{
-public:
-    Glib::Threads::Mutex operation;
-    Glib::Threads::Cond operationCond;
-    Glib::Threads::Mutex GUI;
-    Glib::Threads::Cond GUICond;
-    bool sameThread;
-
-    GThreadLock();
-    ~GThreadLock();
-};
-*/
+// TODO: The documentation says gdk_threads_enter and gdk_threads_leave should be replaced
+// by g_main_context_invoke(), g_idle_add() and related functions, but this will require more extensive changes.
+// We silence those warnings until then so that we notice the others.
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
 
 /**
  * @brief Lock GTK for critical section.
@@ -117,6 +88,7 @@ public:
     }
 };
 
+#pragma GCC diagnostic pop
 
 /**
  * @brief Glue box to control visibility of the MyExpender's content ; also handle the frame around it
````

**Comment by Hombre57** [comment]
Ok, I understand the inheritance problem : BackBuffer is a passive object, where we draw in, and ColoredBar is an active object, which draw on the BackBuffer itself, hence voiding the main characteristic of passivity of its parent class.

Thanks for the tip to avoid the repeating warning message, that's very welcome ! :)

I've pushed the patch, and will look at changing the ColoredBar class later.

For the sc->get_background_color(Gtk::STATE_FLAG_SELECTED), I've set in stone the color values, i.e. it override the theme value, but we have to find a proper workaround. I think that the problem lies in Gtk3 too, because it does send back a value but seem to have some kind of infinite loop.

**Comment by adamreichold** [comment]
I guess the effect of the `Gtk::StyleContext::get_background_color` is to modify the state flags of the state to query the requested colour. But because all thumbnail browser entries share the style context of the `ThumbBrowserBase::internal` widget, this triggers the endless redraw loop. At least saving/restoring the style context state before/after these queries as in the [branch](https://github.com/adamreichold/RawTherapee/tree/isolate-style-state-change) fixed the redraw loop for me.

**Comment by Hombre57** [comment]
See the new "gtk3-renderingLoop" for a bugfix without speed penalty (I hope so). The style is stored in class fields upon realization and when receiving the style_changed event.

Processor activity is now 0% once the thumb has been loaded here (Win7), so I hope it solve the problem for you too.

**Comment by adamreichold** [comment]
@Hombre57 Yes, you change is the more complete fix and does the resolve the issue for me as well. I would maybe suggest to pass the Cairo context as an argument to `ThumbBrowserEntryBase::draw` instead of recreating as in [this version](https://github.com/adamreichold/RawTherapee/tree/gtk3-renderingLoop) of your branch.

**Comment by Hombre57** [comment]
I'm still quite new with GitHub : do anyone know how to apply your patch on my local repo of gtk3-renderingLoop ?

**Comment by adamreichold** [comment]
You can checkout or merge the branch by adding my fork as a remote to your local clone, i.e.
````
# Add remote and fetch contents
> git remote add contrib git@github.com:adamreichold/RawTherapee.git
> git fetch
# Checkout the branch locally
> git checkout -b contrib-gtk3-renderingLoop contrib/gtk3-renderingLoop
# Merge it into your own locally
> git checkout gtk-renderingLoop
> git merge contrib/gtk3-renderingLoop
````

**Comment by Hombre57** [comment]
Hmm, looks like I've fucked up something when pushing the changes. Git is simple, they said... I definitely need a French version of Git client.

**Comment by adamreichold** [comment]
What do you mean? The [branch](https://github.com/Beep6581/RawTherapee/commits/gtk3) seems to look right?

**Comment by Hombre57** [comment]
I did not made a Merge this time, because I wanted to push the local repo of your branch directly, but maybe it would have been better to make a merge as we always do. Now your isolate-style-state-change branch is a dead one. And what I did is "replacing" the current gtk3 branch by mine (the copy of yours) instead of "merging" with conflict resolution. I knew that the change was minor but on a more complex case, I could have fucked things up I guess.

**Comment by adamreichold** [comment]
I see, but I do not think what you fear would happen: If someone would have changed the `gtk3` branch in between your or my `gtk3-renderLoop` changes, pushing the contents of `gtk3-renderLoop` as `gtk3` would be rejected since it would not a fast forward merge (as pushing/pulling is actually merging to remotes (or rebasing if requested)).
Hence I think you would have had needed to use `push --force` which would clearly tell you that something is wrong. And then, all clones of the repository are as good as any other, so as long as other developers have the previous repository contents it can always be restored.

I'd also say we could close this issue since both the actual memory leak and the redraw loop are resolved? Or do we wait for further feedback from the original reporters?

**Comment by Hombre57** [comment]
I already ask for bugfix confirmation, none of the OP answered yet. I'd close it since it's working fine on our build, the OP can still reopen it if ever.

For the fast forward push, you're right, I overlooked that, so it's fine.

**Comment by Coasting** [comment]
I have been out of town and away from my desktop F23 system for a few days. I have not followed the complexities of all the changes and I did not read the entire back and forth about the programming issues and so I missed the "bugfix confirmation" request. 

I'm not quite sure how I confirm--if it is enough to do a pull of the gtk3 branch and compile it in F23 then the fix not working for me but in a new way. [Someone is yet going to make me do a debug version and get a backtrace I think.]

Steps I followed: I did a fresh clone from git. I did "git checkout gtk3" and then compiled to a release version. The program comes up apparently fine. It reports that it is RT 4.2.556. I navigate the browser to the folder containing the 4 copies of DrSlony's amsterdam.pef image. So far so good. No memory leak occurring. I can make some adjustments. I can save the processing profile. However, when I click on the profile selection bar the program crashes in a few seconds. This is also true if I go into "preferences" and then "image processing" and select either of the default profile options to change. It crashes whether the editing window is active or not. In other words, I can open RT, thumbnails for the default folder show in the browser window, and I select a default profile for either raw or jpg and within seconds the program crashes. No big memory leak, just a crash.

I'm invoking RT from a terminal. The terminal message after crashing in the above manner is:
"Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (core dumped)"

If I misunderstood how I should be checking the "fix," let me know and I'll try it again.

Don

**Comment by adamreichold** [comment]
@Coasting I can reproduce your issue and will look into it, but I am also pretty sure this a separate problem. As you noted yourself, this bug report's discussion is already pretty lengthy, so I think this should be handled in a new issue.

**Comment by Coasting** [comment]
@adamreichold  Can I assume you will start the new issue?

**Comment by Hombre57** [comment]
This issue is already open.

**Comment by Hombre57** [comment]
To confirm the fix of the current issue, just survey the memory and processor activity once RT has started and is in a wait state in the FileBrowser : the memory consumption should be stable and the processor idle.

**Comment by Coasting** [comment]
What I meant is that I'm not familiar with the protocols here and so I was not sure that the "fix" was in the gtk3 branch ready to be pulled and checked. With RT-gtk3 pulled today, 4.2.556, the memory is stable and the processor is as idle as it is without RT running. So it seems fixed in the version I pulled.

**Comment by Hombre57** [comment]
Sorry, I misunderstood your comment. Yes, the fix is committed to the gtk3 branch already. Issue can remain closed :)
