### ISSUE TITLE
Handling HDR when stored in a single RAW

### ISSUE THREAD

**Issue by mciepluc** [Beep6581/RawTherapee#5450]
Hello,

I am dealing with a single RAW file (Pentax DNG format) which contains 3 frames - it is supposed to be a HDR image. Unfortunately, I don't know how to use the whole dynamic range. In the demosaicing menu I am able to only choose a single frame of 3. Is handling of such RAWs possilbe in the RT?

THanks

**Comment by Floessie** [comment]
Hi @mciepluc,

Is [HDRMerge](https://jcelaya.github.io/hdrmerge/) a solution for your problem?

Best,
Flössie

**Comment by mciepluc** [comment]
@Floessie not really, I tried HDRMerge but it seems to lose plenty of data when converting to a single RAW. Perfectly, RT should be capable of doing such merge, similarly to what it is able to do (I must admit, quite amazingly) with PixelShift. Maybe someone can share experiences with HDR image processing so I can find a solution that would work for me. Thanks.

**Comment by LigH-de** [comment]
Fujifilm EXR-DR raw files with 2 frames are not yet supported either, but a [feature request](https://github.com/Beep6581/RawTherapee/issues/5407) exists, including a link to a bunch of sample files. If you can provide samples, I guess it may be useful to add their upload location there as well.

HDRMerge is no satisfying solution for me either. Starting with doubts how to use it in case of one file containing several exposure levels (would I have to open this one file several times, once per contained frame?), and wondering what the spread of layer colors tells me.

Adobe Raw Converter can convert my Fujifilm EXR-DR files to HDR-DNG. Their support in RawTherapee 5.6 seems questionable to me, though. Will have to check version 5.7 as well, just read there are some improvements.

My current (extremely elaborate and uncertain) workaround is: exporting the exposure frames with dcraw as TIFF; importing these TIFFs as a stack of LDR images into [Luminance HDR](http://qtpfsgui.sourceforge.net/) while guessing the exposure difference (which is probably wrong); tonemapping to 16 bit PNG or saving the HDR result as EXR or HDR file for other processing tools. Not what I would recommend to other users; still, there are some convenient results.

**Comment by heckflosse** [comment]
@LigH-de 
> HDRMerge is no satisfying solution for me either. Starting with doubts how to use it in case of one file containing several exposure levels (would I have to open this one file several times, once per contained frame?)

If you open an EXR-DR file with two frames in HDRMerge, it loads both frames automatically and then continues as if you would have loaded two raw files.

**Comment by LigH-de** [comment]
Then I would expect to see a few areas of layer 2 (blue) if I load a RAF file with two raw frames with sufficient dynamic range. But I only see a completely green image, and only a layer 1. Tiny bits of a layer 2 appear only when I open the same image twice. But I believe this should rather be discussed in [HDRMerge issue #165](https://github.com/jcelaya/hdrmerge/issues/165) – which is still closed, unfortunately, despite added comments. Or in a new issue in your project.

**Comment by heckflosse** [comment]
Can you start HDRMerge from console with parameter -vv (two v, not one w), then open your file and post the output?
Maybe we should switch to an HDRMerge issue for that?

**Comment by mciepluc** [comment]
I think I can share the same observation as @LigH-de . My HDR RAW single file (Pentax DNG) contains 3 frames and I think the problem is that HDR Merge indeed is not merging these 3 frames into one, so that's why after loading "merged" RAW I could not see any improvment.

**Comment by heckflosse** [comment]
For the Pentax HDR I definitely tested it a while ago and it worked fine. Which HDRMerge version are you using?

**Comment by heckflosse** [comment]
@mciepluc 
>similarly to what it is able to do (I must admit, quite amazingly) with PixelShift.

Thanks for the compliment ;-)

Fot the Pentax 3-in-1 HDR try this build please:
https://keybase.pub/gaaned92/HDRMergeNightlyBuilds/HDRMerge_master_continuous-64-g1408e42_release_64.zip

**Comment by mciepluc** [comment]
Hi @heckflosse 

The nightly build you pointed works OK, HDR is correctly merged and supported just fine by RT. 
The official release of HDRMerge v0.5.0 does not seem to support Pentax 3in1 RAW. 
So this is not an issue with RT at all, so please feel free to close the issue here. 

I am happy with the flow of converting Pentax HDR RAW into single-frame HDR by HDRMerge and then processing it with RT. I have not observed the #5424 issue, is it something already fixed in 5.7? 
Thank you all for help.

**Comment by heckflosse** [comment]
@mciepluc Thanks for feedback :+1: 
> I have not observed the #5424 issue, is it something already fixed in 5.7?

No, iirc it's not yet fixed.
@Beep6581 We should keep an eye on #5424
