### ISSUE TITLE
DNG from Huawei P20 Pro CLT-L29 shows f/0.0 0.0s iso0 0.00mm

### ISSUE THREAD

**Issue by alexkiri** [Beep6581/RawTherapee#6026]
- Version details 
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

- Operating system 
Windows 10 Pro Version 2004 (OS Build 19041.658)

- Steps to reproduce 
Browse to the folder containing the file. Open the DNG file. The top left label shows incorrect parameters

- Raw file
https://drive.google.com/file/d/1LfhReGqXwEKTrI7vui6BYIpMnij3MWrz/view?usp=sharing

- Screenshot
![image](https://user-images.githubusercontent.com/6061770/102258926-1e4b9680-3f17-11eb-9912-a21c447b81ab.png)

**Comment by kmilos** [comment]
I venture this is similar to what was happening in darktable: metadata was only searched for in the Exif IFD, but most smartphone DNGs don't have it (nor is Exif part of the DNG spec to begin with). Most (basic) metadata of the DNG is stored in the main IFD0 instead.

You can check this is indeed the case by e.g. running `exiftool -a -u -s -g1` on this sample.

This was also partly addressed by the ["easy access" API of exiv2](https://github.com/Exiv2/exiv2/pull/1386), so that should also help once RT makes the switch.

**Comment by alexkiri** [comment]
```ExposureTime                    : 30
FNumber                         : 1.8
ISO                             : 3200
DateTimeOriginal                : 2020:08:27 01:41:48
FocalLength                     : 5.6 mm
```

Yup, `exiftool` shows the correct info

**Comment by kmilos** [comment]
They key, however, is where that info is stored in the file: IFD0; there is (normally) no Exif IFD in DNGs (TIFF/EP).

The [location](https://exiftool.org/#groups) you get with the `-g1` (or `-G1`) options of `exiftool`, and you can also tell from the Exif.Image (IFD0) vs Exif.Photo (Exif IFD) [prefix](https://www.exiv2.org/manpage.html#lbAK) when you do `exiv2 -pa`:

```
Exif.Image.FNumber                           Rational    1  F1.8
Exif.Image.ISOSpeedRatings                   Short       1  3200
Exif.Image.DateTimeOriginal                  Ascii      20  2020:08:27 01:41:48
Exif.Image.FocalLength                       Rational    1  5.6 mm
```

**Comment by alexkiri** [comment]
Here is some extra relevant info

```[IFD0]          ExposureTime                    : 30
[IFD0]          FNumber                         : 1.8
[IFD0]          ISO                             : 3200
[IFD0]          DateTimeOriginal                : 2020:08:27 01:41:48
[IFD0]          FocalLength                     : 5.6 mm
[IFD0]          TIFF-EPStandardID               : 1 0 0 0
[IFD0]          DNGVersion                      : 1.4.0.0
[Composite]     Aperture                        : 1.8
[Composite]     ShutterSpeed                    : 30
[Composite]     FocalLength35efl                : 5.6 mm

**Comment by FloBEAUG** [comment]
Hello,
Sorry to re-up but the issue is still there in dev branch (v5.11).
It's annoying as I can't filter the images in the navigation panel.

**Comment by Lawrence37** [comment]
The link to the raw file does not work anymore. Do you have a sample file to share?

**Comment by FloBEAUG** [comment]
> The link to the raw file does not work anymore. Do you have a sample file to share?

Sorry, the problem isn't on dev branch anymore. Thx

**Comment by alexkiri** [comment]
Sorry, I removed the file from drive, I forgot about this issue. I just tested with a new raw file from the same phone, and it appears to work correctly with the latest stable version 5.11. Many thanks! This issue can be closed
