### ISSUE TITLE
RT 5.9 dev shows false colours for Canon 40D photos each time it is rebuilt on linux

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6720]
**Short description**

I have a cron job on my linux PCs which regularly runs the build-rawtherapee script. Whenever the script has downloaded and built an update, RT 5.9 dev will start displaying **all** Canon 40D photos in wildly false colours in the thumbnails and/or in the editor.

**Steps to reproduce**
1. Start newly built RT 5.9 dev
2. Double-click on a folder containing Canon 40D photos.
3. Sometimes the thumbnails appear in normal colours, but when I open them they are shown in false colours in the editor. Other times all the thumbnails are shown in wildly varying false colours and they also show false colours in the editor.
4. Changing the profile of any photo that is shown in false colours to any other profile (whether a bundled profile, one of my saved profiles, or Neutral) doesn't fix the problem.
5. Clearing the cache using options in the UI has no effect on the false colours.
6. This problem only occurs for Canon40D photos for me. It doesn't happen for any of my other cameras, including Canon 7DMkII or Canon G1X.

The following steps can stop the behaviour:
1. Close RT dev.
2. Delete ~/.config/RawTherapee5-dev.
3. Start RT dev.
4. Canon 40D thumbnails look OK, but Editor still show false colours.
5. Close RT dev.
7. Delete ~/.cache/RawTherapee5-dev.
8. Start RT dev
9. Canon 40D thumbnails and Editor show normal colours.

But sometimes even that is not enough and I have to repeat steps 5 through 8 a second time to get it to show the normal colours.

RT 5.9 dev will then show the 40D photos in normal colours until the next time the build-rawtherapee script downloads and builds an update.

**Expected behavior**

The thumbnails and photos in the editor should be displayed in realistic colours. This _does_ happens if I open the same directory in RT 5.8 final that is distributed with Linux Mint 21.1, and also in the RT 5.9 AppImage file.

**Additional information**

This problem happens on 2 different PCs, both running the following software:
OS: Linux Mint 21.1
RT Version: 5.9-128-g5481a8bbe (but the problem has existed for several previous releases).
RT built from source using the build-rawtherapee script:

Version: 5.9-128-g5481a8bbe
Branch: dev
Commit: 5481a8bbe
Commit date: 2023-03-20
Compiler: cc 11.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.15.0-67-generic x86_64
Build date: Mon, 20 Mar 2023 08:00:06 +0000 UTC
Build epoch: 1679299206
Build UUID: 686a76d3-2cc6-4476-89f9-b7da81d26ebf

RT 5.8 showing the same directory as below:
![Screenshot at 2023-02-27 21-11-45](https://user-images.githubusercontent.com/6072789/226444671-bd5151ec-960e-4d31-9ec1-b4c7f882dac1.png)

RT 5.9 dev showing 40D thumbnails in false colours:
![Screenshot at 2023-02-27 21-10-38](https://user-images.githubusercontent.com/6072789/226444577-465f0ee4-6b7d-4440-b329-2013ab8c6adf.png)

RT 5.9 dev showing 40D photo with false colours in the editor:
![Screenshot at 2023-02-27 22-10-19](https://user-images.githubusercontent.com/6072789/226444791-619f9942-9611-4926-a1be-d39e918aa2de.png)

See also: https://discuss.pixls.us/t/solved-false-colours-for-eos-40d-photos-in-5-9-ok-in-5-8/35616

**Comment by ghost** [comment]
I had a go at creating a screen recording demonstrating the problem. At the start it shows the thumbnails in normal colours. When a photo is opened in the editor, it is shown in false colours. The recording shows that changing the profile doesn't fix the false colour. When I switch back to the File Browser the photo's thumbnail now also shows false colours. 

Using 'Select All' and setting any profile in the File Browser makes all the thumbnails show false colours.

Using the Processing profile operations -> Clear option from the context menu in the File Browser resets the selected thumbnails(s) back to normal colours. However, it's not a fix as opening any photo in the editor shows it in false colours again.

https://user-images.githubusercontent.com/6072789/226638244-23981086-c950-4c29-83fd-9b7d8bd387e3.mp4

This recording was made of RT version 5.9-128-g5481a8bbe

**Comment by reticulatus** [comment]
My cron job downloaded and built version 5.9-130-gf84d67f52 earlier today.

I have been running it in a number of sessions since then to check how it is handling the colours in Canon 40D photos. It seems the problem is not as simple as I first believed.

In the first 22 sessions using 5.9-130-gf84d67f52, it showed false colours in 8 of those sessions (36%).

I then deleted the ~/.cache/RawTherapee5-dev/ directory and ran 14 more sessions out of which it showed false colours in 4 of those sessions (29%).

It seems that the occurrence of false colours is intermittent and possibly random. Thus you can't assume that just because a single session shows normal colours that the problem has been fixed. 

I also noticed that in some directories the thumbnails stay in normal colours while they show false colours in the editor. 

Note: if a photo is showing in false colours in the editor and I export it as a jpeg, the jpeg will also be in false colours.

**Comment by ghost** [comment]
Sorry, I hit the wrong button - didn't mean to close this!

**Comment by Lawrence37** [comment]
There seems to be a problem calculating the black levels from the masked sensor regions. The workaround is to remove the `masked_areas` from `camconst.json`. For a user, the workaround is to duplicate the camconst entry to their user config (e.g. `~/.config/RawTherapee5.../camconst.json` and remove the `masked_areas` from the duplicated entry.

**Comment by ghost** [comment]
I copied `camconst.json` to `~/.config/RawTherapee5-dev` and then commented out all the `masked_areas` by prefixing with `//`.

However, the problem was still happening. I then deleted the `~/.cache/RawTherapee5-dev` directory and started RT again. At first it looked like it was working, but after stopping and starting RT several times, the false colours were back:

![Screenshot at 2023-03-26 08-54-40](https://user-images.githubusercontent.com/6072789/227763034-3484a0e9-e559-4ad8-910d-f29def440958.png)

Using version: 5.9-132-g351c9d821

**Comment by Lawrence37** [comment]
@reticulatus @pierre1618
There is a proposed fix in the linked pull request. Please test if you are able to.

**Comment by pierre1618** [comment]
Actually i checked again and i still have the same problem even with the last commit, I think however that it was corrected first, but after using rawtherapee-cli the problem reappeared

**Comment by ghost** [comment]
I have examined a large number of 40D raw photos in the UI, using the pull request fix, and haven't seen any false colours. 

I also used rawtherapee-cli to convert several hundred 40D raw photos to JPEGs. None of the JPEGs appeared in false colours.

**Comment by Lawrence37** [comment]
@pierre1618 I cannot reproduce the issue. What are the exact steps?

**Comment by Lawrence37** [comment]
I merged the proposed fix into `dev` and closed this issue. @pierre1618 if you are able to provide the steps to reproduce the issue, I will take a look.
